name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:    
    runs-on: ubuntu-latest
    steps:
      - name: check branch
        id: check-branch
        run: |
          if [[ ${{ github.ref }} =~ ^refs\/heads\/([A-Z]{3,5}-[0-9]{1,6})_.*$ ]]; then
              echo task_number="${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          fi
      - name: link
        if: steps.check-branch.outputs.task_number
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://st-api.yandex-team.ru/v2/issues/${{ steps.check-branch.outputs.task_number }}'
          method: 'Link'
          customHeaders: '{"Link": "<https://github.com/aalexfvk/test_repo/pull/1>; rel=\"relates\"", "Authorization": "OAuth ${{ secrets.OAUTH_STARTREK }}"}'
          # bearerToken: "OAuth ${{ secrets.OAUTH_STARTREK }}"
        #   url: 'https://st-api.yandex-team.ru/v2/issues/${{ steps.check-branch.outputs.task_number }}/remotelinks'
        #   method: POST
        #   customHeaders: '{"Authorization": "OAuth ${{ secrets.OAUTH_STARTREK }}"}'
        #   data: '{"relationship": "RELATES", "key": "${{ github.server_url }}/${{ github.repository }}", "origin": "CH-BAckup CI/CD"'        
        # uses: satak/webrequest-action@master
        # with:
        #   url: 'https://st-api.yandex-team.ru/v2/issues/${{ steps.check-branch.outputs.task_number }}'
        #   method: LINK
        #   headers: '{"Link": "<https://github.com/aalexfvk/test_repo/pull/1>; rel=\"relates\"", "Authorization": "OAuth ${{ secrets.OAUTH_STARTREK }}"}'
