name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:    
    runs-on: ubuntu-latest
    steps:
      - name: check branch
        id: check-branch
        run: |
          if [[ ${{ github.ref }} =~ ^refs\/heads\/([A-Z]{3,5}-[0-9]{1,6})_.*$ ]]; then
              echo task_number="${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          fi
      - name: link
        if: steps.check-branch.outputs.task_number
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://st-api.yandex-team.ru/v2/issues/${{ steps.check-branch.outputs.task_number }}'
          method: 'LINK'
          customHeaders: >
            '{
               "Link": "${{ github.server_url }}/${{ github.repository }}/"; rel="relates"",
             }'
          bearerToken: OAuth ${{ secrets.OAUTH_STARTREK }}
        
