name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    branches:
    - main
jobs:
  Link-With-Startrek:    
    runs-on: ubuntu-latest
    steps:
      - name: parse branch
        id: parse-branch
        run: |
          if [[ ${{ github.head_ref }} =~ ^refs\/heads\/([A-Za-z]+\-[0-9]+)_.*$ ]]; then
              echo issue_number="${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          fi
      - name: link with startrek
        if: steps.check-branch.outputs.issue_number
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://st-api.yandex-team.ru/v2/issues/${{ steps.check-branch.outputs.issue_number }}'
          method: 'LINK'
          customHeaders: '{"Link": "<${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}>; rel=\"relates\"", "Authorization": "OAuth ${{ secrets.OAUTH_STARTREK }}"}'
